import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'om' | 'am';

const translations = {
  en: {
    welcome: 'Welcome to Knowledge Universe',
    subtitle: 'Explore Knowledge in a Digital Universe',
    tagline: 'Read • Learn • Track • Grow',
    startLearning: 'Start Learning',
    exploreBooks: 'Explore Books',
    askAI: 'Ask AI Tutor',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Full Name',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    role: 'Select Role',
    student: 'Student',
    teacher: 'Teacher',
    school: 'School',
    language: 'Language',
    dashboard: 'Dashboard',
    library: 'Library',
    aiTutor: 'AI Tutor',
    quiz: 'Quiz',
    pricing: 'Pricing',
    contact: 'Contact',
    admin: 'Admin',
    galaxy: 'Galaxy Explorer',
    continueReading: 'Continue Reading',
    startQuiz: 'Start Quiz',
    studyAnalytics: 'Study Analytics',
    dailyStreak: 'Daily Streak',
    leaderboard: 'Leaderboard',
    recentBooks: 'Recent Books',
    xpPoints: 'XP Points',
    booksRead: 'Books Read',
    studyTime: 'Study Time',
    quizScore: 'Quiz Score',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    selectLanguage: 'Select Language',
    upgradeNow: 'Upgrade Now',
    free: 'Free',
    premium: 'Premium',
    perMonth: '/month',
    perYear: '/year',
    sendMessage: 'Send Message',
    typeMessage: 'Type your message...',
    uploadPDF: 'Upload PDF',
    createQuiz: 'Create Quiz',
    manageUsers: 'Manage Users',
    analytics: 'Analytics',
    announcements: 'Announcements',
    grade: 'Grade',
    subject: 'Subject',
    search: 'Search...',
    mathematics: 'Mathematics',
    physics: 'Physics',
    chemistry: 'Chemistry',
    biology: 'Biology',
    geography: 'Geography',
    history: 'History',
    economics: 'Economics',
    english: 'English',
    afanOromo: 'Afan Oromo',
    settings: 'Settings',
  },
  om: {
    welcome: 'Baga Nagaan Gara Knowledge Universe Dhuftan',
    subtitle: "Beekumsa Addunyaa Dijitaalaa Keessatti Qo'adha",
    tagline: "Dubbisi • Barri • Hordofi • Guddadhu",
    startLearning: "Barachuu Jalqaba",
    exploreBooks: 'Kitaabota Sakatta\'i',
    askAI: 'AI Barsiisaa Gaafadhu',
    login: 'Seeni',
    register: "Galmaa'i",
    email: 'Imeelii',
    password: 'Jecha Darbii',
    confirmPassword: 'Jecha Darbii Mirkaneessi',
    name: 'Maqaa Guutuu',
    rememberMe: 'Na yaadadhu',
    forgotPassword: 'Jecha darbii dagatte?',
    role: 'Gahee Filadhu',
    student: 'Barataa',
    teacher: 'Barsiisaa',
    school: 'Mana Barumsaa',
    language: 'Afaan',
    dashboard: 'Kontiroolii',
    library: 'Mana Kitaabaa',
    aiTutor: 'AI Barsiisaa',
    quiz: 'Qormaata',
    pricing: 'Gatii',
    contact: "Qunnamtii",
    admin: 'Bulchiinsa',
    galaxy: "Galaksii Qo'annoo",
    continueReading: 'Dubbisuu Itti Fufi',
    startQuiz: 'Qormaata Jalqabi',
    studyAnalytics: "Xiinxala Qo'annoo",
    dailyStreak: 'Tartiiba Guyyaa',
    leaderboard: 'Sadarkaa',
    recentBooks: 'Kitaabota Dhiyoo',
    xpPoints: 'Qabxii XP',
    booksRead: 'Kitaabota Dubbifaman',
    studyTime: "Yeroo Qo'annoo",
    quizScore: 'Qabxii Qormaataa',
    noAccount: "Herrega hin qabduu?",
    haveAccount: "Herrega qabdaa?",
    signUp: "Galmaa'i",
    signIn: 'Seeni',
    selectLanguage: 'Afaan Filadhu',
    upgradeNow: 'Amma Fooyyessi',
    free: 'Bilisaa',
    premium: 'Pirimiyeemii',
    perMonth: '/ji\'a',
    perYear: '/waggaa',
    sendMessage: "Ergaa Ergi",
    typeMessage: "Ergaa kee barreessi...",
    uploadPDF: "PDF Olkaa'i",
    createQuiz: 'Qormaata Uumi',
    manageUsers: 'Fayyadamtoota Bulchi',
    analytics: 'Xiinxala',
    announcements: 'Beeksisa',
    grade: 'Kutaa',
    subject: 'Barnoota',
    search: "Barbaadi...",
    mathematics: 'Herrega',
    physics: 'Fiiziiksii',
    chemistry: 'Keemiistirii',
    biology: 'Bayoloojii',
    geography: "Jii'oogiraafii",
    history: 'Seenaa',
    economics: 'Ikoonomiksii',
    english: 'Afaan Ingilizii',
    afanOromo: 'Afaan Oromoo',
    settings: 'Sajoota',
  },
  am: {
    welcome: 'ወደ Knowledge Universe እንኳን ደህና መጡ',
    subtitle: 'በዲጂታል ዓለም ውስጥ ዕውቀትን ያስሱ',
    tagline: 'ያንብቡ • ይማሩ • ይከታተሉ • ያድጉ',
    startLearning: 'መማር ይጀምሩ',
    exploreBooks: 'መጻሕፍትን ያስሱ',
    askAI: 'AI አስተማሪን ይጠይቁ',
    login: 'ግባ',
    register: 'ተመዝገብ',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
    name: 'ሙሉ ስም',
    rememberMe: 'አስታውሰኝ',
    forgotPassword: 'የይለፍ ቃል ረሱ?',
    role: 'ሚና ይምረጡ',
    student: 'ተማሪ',
    teacher: 'መምህር',
    school: 'ትምህርት ቤት',
    language: 'ቋንቋ',
    dashboard: 'ዳሽቦርድ',
    library: 'ቤተ መጻሕፍት',
    aiTutor: 'AI አስተማሪ',
    quiz: 'ፈተና',
    pricing: 'ዋጋ',
    contact: 'ያግኙን',
    admin: 'አስተዳደር',
    galaxy: 'ጋላክሲ አሳሽ',
    continueReading: 'ማንበብ ይቀጥሉ',
    startQuiz: 'ፈተና ይጀምሩ',
    studyAnalytics: 'የጥናት ትንተና',
    dailyStreak: 'ዕለታዊ ተከታታይነት',
    leaderboard: 'ደረጃ ሰሌዳ',
    recentBooks: 'የቅርብ ጊዜ መጻሕፍት',
    xpPoints: 'XP ነጥቦች',
    booksRead: 'የተነበቡ መጻሕፍት',
    studyTime: 'የጥናት ጊዜ',
    quizScore: 'የፈተና ውጤት',
    noAccount: 'መለያ የለዎትም?',
    haveAccount: 'መለያ አለዎት?',
    signUp: 'ተመዝገብ',
    signIn: 'ግባ',
    selectLanguage: 'ቋንቋ ይምረጡ',
    upgradeNow: 'አሁን ያሻሽሉ',
    free: 'ነፃ',
    premium: 'ፕሪሚየም',
    perMonth: '/ወር',
    perYear: '/ዓመት',
    sendMessage: 'መልዕክት ይላኩ',
    typeMessage: 'መልዕክትዎን ይጻፉ...',
    uploadPDF: 'PDF ይጫኑ',
    createQuiz: 'ፈተና ይፍጠሩ',
    manageUsers: 'ተጠቃሚዎችን ያስተዳድሩ',
    analytics: 'ትንተና',
    announcements: 'ማስታወቂያዎች',
    grade: 'ክፍል',
    subject: 'ትምህርት',
    search: 'ይፈልጉ...',
    mathematics: 'ሂሳብ',
    physics: 'ፊዚክስ',
    chemistry: 'ኬሚስትሪ',
    biology: 'ባዮሎጂ',
    geography: 'ጂኦግራፊ',
    history: 'ታሪክ',
    economics: 'ኢኮኖሚክስ',
    english: 'እንግሊዝኛ',
    afanOromo: 'አፋን ኦሮሞ',
    settings: 'ቅንብሮች',
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
